services:
  tao:
    build:
      context: ../
      dockerfile: Dockerfile.custom
    depends_on:
      - database
    volumes:
      - tao-code:/var/www/html
    environment:
      DB_HOST: ${DB_HOST:-database}
      DB_NAME: ${DB_NAME:-tao}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-r00t}
      USER: ${ADMIN_USER:-admin}
      PASSWORD: ${ADMIN_PASSWORD:-admin123}
      URL: ${TAO_URL:-http://localhost}
      TZ: Asia/Kolkata

  web:
    image: nginx:1.19
    ports:
      - "80:80"
    depends_on:
      - tao
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - tao-code:/var/www/html
    environment:
      TZ: Asia/Kolkata

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-r00t}
      MYSQL_USER: tao
      MYSQL_PASSWORD: ${DB_PASSWORD:-r00t}
      MYSQL_DATABASE: ${DB_NAME:-tao}
      TZ: Asia/Kolkata
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='+05:30'
    cap_add:
      - SYS_NICE

volumes:
  tao-code:
